# OneHotEncoding

A method of turning categorical data into boolean data

In [29]:
import pandas as pd
data = ['male','male','male','male','male','female','male','male','female','male','male','male','male','female','female']

gender_df = pd.DataFrame(data, columns = ['Gender'])
gender_df.head()

  Gender
0   male
1   male
2   male
3   male
4   male

In [54]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
label_encoded = le.fit_transform(gender_df.Gender)
print(label_encoded)
gender_encodeddf = pd.DataFrame(label_encoded , columns = ['GenderEncoded']) 
gender_encodeddf.head()
gender_encodeddf

[1 1 1 1 1 0 1 1 0 1 1 1 1 0 0]

    GenderEncoded
0               1
1               1
2               1
3               1
4               1
5               0
6               1
7               1
8               0
9               1
10              1
11              1
12              1
13              0
14              0

In [55]:
from sklearn.preprocessing import OneHotEncoder

# creating an instance of the class
ohe = OneHotEncoder()
one_encoded =ohe.fit_transform(gender_encodeddf[['GenderEncoded']])
one_encodeddf = pd.DataFrame(one_encoded, columns = ['Gender_OneHotEncoded'])
one_encodeddf

ValueError: Shape of passed values is (15, 2), indices imply (15, 1)

In [65]:
# creating dummies as an alternative to onehotencoding
dummies = pd.get_dummies(gender_encodeddf['GenderEncoded'])
dummiesdf = pd.DataFrame(dummies)
dummiesdf
concatenated = pd.concat([gender_df,dummiesdf],axis = 1)
concatenated

    Gender  0  1
0     male  0  1
1     male  0  1
2     male  0  1
3     male  0  1
4     male  0  1
5   female  1  0
6     male  0  1
7     male  0  1
8   female  1  0
9     male  0  1
10    male  0  1
11    male  0  1
12    male  0  1
13  female  1  0
14  female  1  0

Useful Links
https://towardsdatascience.com/one-hot-encoding-is-making-your-tree-based-ensembles-worse-heres-why-d64b282b5769